### ISSUE TITLE
Negative currency amount results in NaN in IE11/Chrome

### ISSUE THREAD

**Issue by chrisgalanek** [wemersonjanuario/Ext.ux.form.field.Currency#1]
When changing a currency amount to a negative number, the result in the field is a "NaN error" that the number is not valid.  I was able to fix this by changing line 109 as follows:

From:
return Ext.String.format('{0}{1}{2}', (neg ? '-' : ''), position1, position2);

To:
return Ext.String.format('{0}{1}{2}',  position1, (neg ? '-' : ''), position2);

**Comment by wemersonjanuario** [comment]
Thanks man for contributing. Fixed
